version: '3'

services:

  zookeeper:
    container_name: zookeeper
    image: zookeeper
    ports:
      - "2181:2181"
    restart: always

  kafka:
    container_name: kafka
    image: ches/kafka
    ports:
      - "9092:9092"
      - "7203:7203"
    depends_on:
      - zookeeper
    links:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.0.75.1
      ZOOKEEPER_IP: zookeeper
      ZOOKEEPER_PORT: 2181
    volumes:
      - ./data/kafka:/data
      - ./logs/kafka:/logs
    restart: always

  nimbus:
    container_name: nimbus
    image: storm
    command: storm nimbus
    ports:
      - "6627:6627"
    depends_on:
      - zookeeper
    links:
      - zookeeper
    volumes:
      - ./data/storm/nimbus:/data
      - ./logs/storm/nimbus:/logs
    restart: always

  supervisor:
    container_name: supervisor
    image: storm
    command: storm supervisor
    ports:
      - "8000:8000"
    depends_on:
      - nimbus
      - zookeeper
    links:
      - nimbus
      - zookeeper
    volumes:
      - ./data/storm/supervisor:/data
      - ./logs/storm/supervisor:/logs
    restart: always

  storm:
    container_name: storm
    image: storm
    command: storm ui
    ports:
      - "8090:8080"
    depends_on:
      - nimbus
      - supervisor
      - zookeeper
    links:
      - nimbus
      - supervisor
      - zookeeper
    restart: always